apiVersion: v1
kind: Service
metadata:
  name: thirarum-webchat
  labels:
    app: thirarum-webchat
spec:
  selector:
    app: thirarum-webchat
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
